DOC: Update requirements to prevent PyMC3 installation error
without restriction pymc3<3.7, Python 3.5.2 cannot be used due to error
ERROR: pymc3 requires Python '>=3.5.4' but the running Python is 3.5.2